params:  

  seed: 42
  
  env:
    clip_observations: 100.0
    clip_actions: 100.0

  algo:
    name: sac

  model:
    name: soft_actor_critic

  network:
    name: soft_actor_critic
    separate: True
    space:
      continuous:
    mlp:
      units: [64, 64]
      activation: relu
      
      initializer:
        name: default
    log_std_bounds: [-5, 2]

  load_checkpoint: False
  load_path: ''

  config:
    name: ur3_reach_direct
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    normalize_input: True
    reward_shaper:
      scale_value: 1.0
    max_epochs: 20000
    num_steps_per_episode: 500
    save_best_after: 100
    save_frequency: 1000
    gamma: 0.99
    init_alpha: 1.0
    alpha_lr: 0.005
    actor_lr: 0.0005
    critic_lr: 0.0005
    critic_tau: 0.005
    batch_size: 4096
    learnable_temperature: true
    num_seed_steps: 5
    num_warmup_steps: 10
    replay_buffer_size: 1000000
    num_actors: 512